// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UseSenseHostApi {
  func initialize(config: PigeonUseSenseConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func startVerification(request: PigeonVerificationRequest, completion: @escaping (Result<PigeonUseSenseResult, Error>) -> Void)
  func startRemoteEnrollment(remoteEnrollmentId: String, completion: @escaping (Result<PigeonUseSenseResult, Error>) -> Void)
  func startRemoteVerification(remoteSessionId: String, completion: @escaping (Result<PigeonUseSenseResult, Error>) -> Void)
  func isInitialized() throws -> Bool
  func reset() throws
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
class UseSenseFlutterApiImpl {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String

  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }

  var codec: FlutterStandardMessageCodec { UseSensePigeonCodec.shared }

  func onEvent(event: PigeonUseSenseEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName = "dev.flutter.pigeon.usesense_flutter.UseSenseFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([event.toList()] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }

  func onCancelled(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName = "dev.flutter.pigeon.usesense_flutter.UseSenseFlutterApi.onCancelled\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: listResponse[0] as! String, message: listResponse[1] as? String, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

enum PigeonUseSenseEnvironment: Int {
  case sandbox = 0
  case production = 1
  case auto = 2
}

enum PigeonSessionType: Int {
  case enrollment = 0
  case authentication = 1
}

enum PigeonEventType: Int {
  case sessionCreated = 0
  case permissionsRequested = 1
  case permissionsGranted = 2
  case permissionsDenied = 3
  case captureStarted = 4
  case frameCaptured = 5
  case captureCompleted = 6
  case audioRecordStarted = 7
  case audioRecordCompleted = 8
  case challengeStarted = 9
  case challengeCompleted = 10
  case uploadStarted = 11
  case uploadProgress = 12
  case uploadCompleted = 13
  case completeStarted = 14
  case decisionReceived = 15
  case imageQualityCheck = 16
  case error = 17
}

// ---------------------------------------------------------------------------
// Data classes
// ---------------------------------------------------------------------------

struct PigeonBrandingConfig {
  var displayName: String?
  var logoUrl: String?
  var primaryColor: String?
  var redirectUrl: String?
  var buttonRadius: Int64?
  var fontFamily: String?

  func toList() -> [Any?] {
    return [displayName, logoUrl, primaryColor, redirectUrl, buttonRadius, fontFamily]
  }

  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonBrandingConfig {
    return PigeonBrandingConfig(
      displayName: nilOrValue(pigeonVar_list[0]),
      logoUrl: nilOrValue(pigeonVar_list[1]),
      primaryColor: nilOrValue(pigeonVar_list[2]),
      redirectUrl: nilOrValue(pigeonVar_list[3]),
      buttonRadius: nilOrValue(pigeonVar_list[4]),
      fontFamily: nilOrValue(pigeonVar_list[5])
    )
  }
}

struct PigeonUseSenseConfig {
  var apiKey: String
  var environment: PigeonUseSenseEnvironment
  var baseUrl: String?
  var gatewayKey: String?
  var branding: PigeonBrandingConfig?
  var googleCloudProjectNumber: Int64?

  func toList() -> [Any?] {
    return [apiKey, environment.rawValue, baseUrl, gatewayKey, branding?.toList(), googleCloudProjectNumber]
  }

  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonUseSenseConfig {
    let branding: PigeonBrandingConfig? = nilOrValue(pigeonVar_list[4]) != nil
      ? PigeonBrandingConfig.fromList(pigeonVar_list[4] as! [Any?])
      : nil
    return PigeonUseSenseConfig(
      apiKey: pigeonVar_list[0] as! String,
      environment: PigeonUseSenseEnvironment(rawValue: pigeonVar_list[1] as! Int)!,
      baseUrl: nilOrValue(pigeonVar_list[2]),
      gatewayKey: nilOrValue(pigeonVar_list[3]),
      branding: branding,
      googleCloudProjectNumber: nilOrValue(pigeonVar_list[5])
    )
  }
}

struct PigeonVerificationRequest {
  var sessionType: PigeonSessionType
  var externalUserId: String?
  var identityId: String?
  var metadata: [String: String]?

  func toList() -> [Any?] {
    return [sessionType.rawValue, externalUserId, identityId, metadata]
  }

  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonVerificationRequest {
    return PigeonVerificationRequest(
      sessionType: PigeonSessionType(rawValue: pigeonVar_list[0] as! Int)!,
      externalUserId: nilOrValue(pigeonVar_list[1]),
      identityId: nilOrValue(pigeonVar_list[2]),
      metadata: nilOrValue(pigeonVar_list[3])
    )
  }
}

struct PigeonUseSenseResult {
  var sessionId: String
  var sessionType: String?
  var identityId: String?
  var decision: String
  var timestamp: String

  func toList() -> [Any?] {
    return [sessionId, sessionType, identityId, decision, timestamp]
  }

  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonUseSenseResult {
    return PigeonUseSenseResult(
      sessionId: pigeonVar_list[0] as! String,
      sessionType: nilOrValue(pigeonVar_list[1]),
      identityId: nilOrValue(pigeonVar_list[2]),
      decision: pigeonVar_list[3] as! String,
      timestamp: pigeonVar_list[4] as! String
    )
  }
}

struct PigeonUseSenseEvent {
  var type: PigeonEventType
  var timestamp: Int64
  var data: [String: Any?]?

  func toList() -> [Any?] {
    return [type.rawValue, timestamp, data]
  }

  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonUseSenseEvent {
    return PigeonUseSenseEvent(
      type: PigeonEventType(rawValue: pigeonVar_list[0] as! Int)!,
      timestamp: pigeonVar_list[1] as! Int64,
      data: nilOrValue(pigeonVar_list[2])
    )
  }
}

struct PigeonUseSenseError {
  var code: Int64
  var serverCode: String?
  var message: String
  var isRetryable: Bool
  var details: [String: String]?

  func toList() -> [Any?] {
    return [code, serverCode, message, isRetryable, details]
  }

  static func fromList(_ pigeonVar_list: [Any?]) -> PigeonUseSenseError {
    return PigeonUseSenseError(
      code: pigeonVar_list[0] as! Int64,
      serverCode: nilOrValue(pigeonVar_list[1]),
      message: pigeonVar_list[2] as! String,
      isRetryable: pigeonVar_list[3] as! Bool,
      details: nilOrValue(pigeonVar_list[4])
    )
  }
}

// ---------------------------------------------------------------------------
// Codec
// ---------------------------------------------------------------------------

class UseSensePigeonCodec: FlutterStandardMessageCodec {
  static let shared = UseSensePigeonCodec(readerWriter: UseSensePigeonCodecReaderWriter())
}

private class UseSensePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UseSensePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UseSensePigeonCodecWriter(data: data)
  }
}

private class UseSensePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129: return PigeonBrandingConfig.fromList(readValue() as! [Any?])
    case 130: return PigeonUseSenseConfig.fromList(readValue() as! [Any?])
    case 131: return PigeonVerificationRequest.fromList(readValue() as! [Any?])
    case 132: return PigeonUseSenseResult.fromList(readValue() as! [Any?])
    case 133: return PigeonUseSenseEvent.fromList(readValue() as! [Any?])
    case 134: return PigeonUseSenseError.fromList(readValue() as! [Any?])
    default: return super.readValue(ofType: type)
    }
  }
}

private class UseSensePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let v = value as? PigeonBrandingConfig {
      writeByte(129)
      writeValue(v.toList())
    } else if let v = value as? PigeonUseSenseConfig {
      writeByte(130)
      writeValue(v.toList())
    } else if let v = value as? PigeonVerificationRequest {
      writeByte(131)
      writeValue(v.toList())
    } else if let v = value as? PigeonUseSenseResult {
      writeByte(132)
      writeValue(v.toList())
    } else if let v = value as? PigeonUseSenseEvent {
      writeByte(133)
      writeValue(v.toList())
    } else if let v = value as? PigeonUseSenseError {
      writeByte(134)
      writeValue(v.toList())
    } else {
      super.writeValue(value)
    }
  }
}

// ---------------------------------------------------------------------------
// Error & helpers
// ---------------------------------------------------------------------------

class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as? T
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [pigeonError.code, pigeonError.message, pigeonError.details]
  }
  if let flutterError = error as? FlutterError {
    return [flutterError.code, flutterError.message, flutterError.details]
  }
  return ["\(error)", "\(error)", nil]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

// ---------------------------------------------------------------------------
// Host API setup
// ---------------------------------------------------------------------------

func UseSenseHostApiSetup(_ binaryMessenger: FlutterBinaryMessenger, _ api: UseSenseHostApi?, messageChannelSuffix: String = "") {
  let suffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  let codec = UseSensePigeonCodec.shared

  let initializeChannel = FlutterBasicMessageChannel(
    name: "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.initialize\(suffix)",
    binaryMessenger: binaryMessenger,
    codec: codec
  )
  if let api = api {
    initializeChannel.setMessageHandler { message, reply in
      let args = message as! [Any?]
      let configArg = args[0] as! PigeonUseSenseConfig
      api.initialize(config: configArg) { result in
        switch result {
        case .success:
          reply(wrapResult(nil))
        case .failure(let error):
          reply(wrapError(error))
        }
      }
    }
  } else {
    initializeChannel.setMessageHandler(nil)
  }

  let startVerificationChannel = FlutterBasicMessageChannel(
    name: "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.startVerification\(suffix)",
    binaryMessenger: binaryMessenger,
    codec: codec
  )
  if let api = api {
    startVerificationChannel.setMessageHandler { message, reply in
      let args = message as! [Any?]
      let requestArg = args[0] as! PigeonVerificationRequest
      api.startVerification(request: requestArg) { result in
        switch result {
        case .success(let res):
          reply(wrapResult(res.toList()))
        case .failure(let error):
          reply(wrapError(error))
        }
      }
    }
  } else {
    startVerificationChannel.setMessageHandler(nil)
  }

  let startRemoteEnrollmentChannel = FlutterBasicMessageChannel(
    name: "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.startRemoteEnrollment\(suffix)",
    binaryMessenger: binaryMessenger,
    codec: codec
  )
  if let api = api {
    startRemoteEnrollmentChannel.setMessageHandler { message, reply in
      let args = message as! [Any?]
      let remoteEnrollmentIdArg = args[0] as! String
      api.startRemoteEnrollment(remoteEnrollmentId: remoteEnrollmentIdArg) { result in
        switch result {
        case .success(let res):
          reply(wrapResult(res.toList()))
        case .failure(let error):
          reply(wrapError(error))
        }
      }
    }
  } else {
    startRemoteEnrollmentChannel.setMessageHandler(nil)
  }

  let startRemoteVerificationChannel = FlutterBasicMessageChannel(
    name: "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.startRemoteVerification\(suffix)",
    binaryMessenger: binaryMessenger,
    codec: codec
  )
  if let api = api {
    startRemoteVerificationChannel.setMessageHandler { message, reply in
      let args = message as! [Any?]
      let remoteSessionIdArg = args[0] as! String
      api.startRemoteVerification(remoteSessionId: remoteSessionIdArg) { result in
        switch result {
        case .success(let res):
          reply(wrapResult(res.toList()))
        case .failure(let error):
          reply(wrapError(error))
        }
      }
    }
  } else {
    startRemoteVerificationChannel.setMessageHandler(nil)
  }

  let isInitializedChannel = FlutterBasicMessageChannel(
    name: "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.isInitialized\(suffix)",
    binaryMessenger: binaryMessenger,
    codec: codec
  )
  if let api = api {
    isInitializedChannel.setMessageHandler { _, reply in
      do {
        let result = try api.isInitialized()
        reply(wrapResult(result))
      } catch {
        reply(wrapError(error))
      }
    }
  } else {
    isInitializedChannel.setMessageHandler(nil)
  }

  let resetChannel = FlutterBasicMessageChannel(
    name: "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.reset\(suffix)",
    binaryMessenger: binaryMessenger,
    codec: codec
  )
  if let api = api {
    resetChannel.setMessageHandler { _, reply in
      do {
        try api.reset()
        reply(wrapResult(nil))
      } catch {
        reply(wrapError(error))
      }
    }
  } else {
    resetChannel.setMessageHandler(nil)
  }
}
