// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.usesense.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(exception.code, exception.message, exception.details)
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: ${exception.cause}, Stacktrace: ${Log.getStackTraceString(exception)}"
    )
  }
}

/** An error thrown by the generated Pigeon code. */
class FlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null,
) : Throwable()

/** The target environment for the UseSense backend. */
enum class PigeonUseSenseEnvironment(val raw: Int) {
  SANDBOX(0),
  PRODUCTION(1),
  AUTO(2);

  companion object {
    fun ofRaw(raw: Int): PigeonUseSenseEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The type of verification session. */
enum class PigeonSessionType(val raw: Int) {
  ENROLLMENT(0),
  AUTHENTICATION(1);

  companion object {
    fun ofRaw(raw: Int): PigeonSessionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Event types emitted during a verification session. */
enum class PigeonEventType(val raw: Int) {
  SESSION_CREATED(0),
  PERMISSIONS_REQUESTED(1),
  PERMISSIONS_GRANTED(2),
  PERMISSIONS_DENIED(3),
  CAPTURE_STARTED(4),
  FRAME_CAPTURED(5),
  CAPTURE_COMPLETED(6),
  AUDIO_RECORD_STARTED(7),
  AUDIO_RECORD_COMPLETED(8),
  CHALLENGE_STARTED(9),
  CHALLENGE_COMPLETED(10),
  UPLOAD_STARTED(11),
  UPLOAD_PROGRESS(12),
  UPLOAD_COMPLETED(13),
  COMPLETE_STARTED(14),
  DECISION_RECEIVED(15),
  IMAGE_QUALITY_CHECK(16),
  ERROR(17);

  companion object {
    fun ofRaw(raw: Int): PigeonEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Branding configuration for the SDK UI. */
data class PigeonBrandingConfig(
  val displayName: String? = null,
  val logoUrl: String? = null,
  val primaryColor: String? = null,
  val redirectUrl: String? = null,
  val buttonRadius: Long? = null,
  val fontFamily: String? = null,
) {
  fun toList(): List<Any?> {
    return listOf(displayName, logoUrl, primaryColor, redirectUrl, buttonRadius, fontFamily)
  }

  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PigeonBrandingConfig {
      return PigeonBrandingConfig(
        displayName = pigeonVar_list[0] as String?,
        logoUrl = pigeonVar_list[1] as String?,
        primaryColor = pigeonVar_list[2] as String?,
        redirectUrl = pigeonVar_list[3] as String?,
        buttonRadius = pigeonVar_list[4] as Long?,
        fontFamily = pigeonVar_list[5] as String?,
      )
    }
  }
}

/** SDK configuration. */
data class PigeonUseSenseConfig(
  val apiKey: String,
  val environment: PigeonUseSenseEnvironment = PigeonUseSenseEnvironment.AUTO,
  val baseUrl: String? = null,
  val gatewayKey: String? = null,
  val branding: PigeonBrandingConfig? = null,
  val googleCloudProjectNumber: Long? = null,
) {
  fun toList(): List<Any?> {
    return listOf(apiKey, environment.raw, baseUrl, gatewayKey, branding?.toList(), googleCloudProjectNumber)
  }

  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PigeonUseSenseConfig {
      return PigeonUseSenseConfig(
        apiKey = pigeonVar_list[0] as String,
        environment = PigeonUseSenseEnvironment.ofRaw(pigeonVar_list[1] as Int)!!,
        baseUrl = pigeonVar_list[2] as String?,
        gatewayKey = pigeonVar_list[3] as String?,
        branding = (pigeonVar_list[4] as List<Any?>?)?.let { PigeonBrandingConfig.fromList(it) },
        googleCloudProjectNumber = pigeonVar_list[5] as Long?,
      )
    }
  }
}

/** Request to start a verification session. */
data class PigeonVerificationRequest(
  val sessionType: PigeonSessionType,
  val externalUserId: String? = null,
  val identityId: String? = null,
  val metadata: Map<String, String>? = null,
) {
  fun toList(): List<Any?> {
    return listOf(sessionType.raw, externalUserId, identityId, metadata)
  }

  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(pigeonVar_list: List<Any?>): PigeonVerificationRequest {
      return PigeonVerificationRequest(
        sessionType = PigeonSessionType.ofRaw(pigeonVar_list[0] as Int)!!,
        externalUserId = pigeonVar_list[1] as String?,
        identityId = pigeonVar_list[2] as String?,
        metadata = pigeonVar_list[3] as Map<String, String>?,
      )
    }
  }
}

/** The outcome of a completed verification session. */
data class PigeonUseSenseResult(
  val sessionId: String,
  val sessionType: String? = null,
  val identityId: String? = null,
  val decision: String,
  val timestamp: String,
) {
  fun toList(): List<Any?> {
    return listOf(sessionId, sessionType, identityId, decision, timestamp)
  }

  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PigeonUseSenseResult {
      return PigeonUseSenseResult(
        sessionId = pigeonVar_list[0] as String,
        sessionType = pigeonVar_list[1] as String?,
        identityId = pigeonVar_list[2] as String?,
        decision = pigeonVar_list[3] as String,
        timestamp = pigeonVar_list[4] as String,
      )
    }
  }
}

/** An event emitted during a verification session. */
data class PigeonUseSenseEvent(
  val type: PigeonEventType,
  val timestamp: Long,
  val data: Map<String, Any?>? = null,
) {
  fun toList(): List<Any?> {
    return listOf(type.raw, timestamp, data)
  }

  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(pigeonVar_list: List<Any?>): PigeonUseSenseEvent {
      return PigeonUseSenseEvent(
        type = PigeonEventType.ofRaw(pigeonVar_list[0] as Int)!!,
        timestamp = pigeonVar_list[1] as Long,
        data = pigeonVar_list[2] as Map<String, Any?>?,
      )
    }
  }
}

/** Structured error from the native SDK. */
data class PigeonUseSenseError(
  val code: Long,
  val serverCode: String? = null,
  val message: String,
  val isRetryable: Boolean = false,
  val details: Map<String, String>? = null,
) {
  fun toList(): List<Any?> {
    return listOf(code, serverCode, message, isRetryable, details)
  }

  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(pigeonVar_list: List<Any?>): PigeonUseSenseError {
      return PigeonUseSenseError(
        code = pigeonVar_list[0] as Long,
        serverCode = pigeonVar_list[1] as String?,
        message = pigeonVar_list[2] as String,
        isRetryable = pigeonVar_list[3] as Boolean,
        details = pigeonVar_list[4] as Map<String, String>?,
      )
    }
  }
}

private object UseSensePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> PigeonBrandingConfig.fromList(readValue(buffer) as List<Any?>)
      130.toByte() -> PigeonUseSenseConfig.fromList(readValue(buffer) as List<Any?>)
      131.toByte() -> PigeonVerificationRequest.fromList(readValue(buffer) as List<Any?>)
      132.toByte() -> PigeonUseSenseResult.fromList(readValue(buffer) as List<Any?>)
      133.toByte() -> PigeonUseSenseEvent.fromList(readValue(buffer) as List<Any?>)
      134.toByte() -> PigeonUseSenseError.fromList(readValue(buffer) as List<Any?>)
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    when (value) {
      is PigeonBrandingConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PigeonUseSenseConfig -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PigeonVerificationRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PigeonUseSenseResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PigeonUseSenseEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PigeonUseSenseError -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UseSenseHostApi {
  fun initialize(config: PigeonUseSenseConfig, callback: (Result<Unit>) -> Unit)
  fun startVerification(request: PigeonVerificationRequest, callback: (Result<PigeonUseSenseResult>) -> Unit)
  fun startRemoteEnrollment(remoteEnrollmentId: String, callback: (Result<PigeonUseSenseResult>) -> Unit)
  fun startRemoteVerification(remoteSessionId: String, callback: (Result<PigeonUseSenseResult>) -> Unit)
  fun isInitialized(): Boolean
  fun reset()

  companion object {
    val codec: MessageCodec<Any?> by lazy { UseSensePigeonCodec }

    fun setUp(binaryMessenger: BinaryMessenger, api: UseSenseHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.initialize$separatedMessageChannelSuffix",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as PigeonUseSenseConfig
            api.initialize(configArg) { result ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.startVerification$separatedMessageChannelSuffix",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonVerificationRequest
            api.startVerification(requestArg) { result ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(result.getOrNull()))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.startRemoteEnrollment$separatedMessageChannelSuffix",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteEnrollmentIdArg = args[0] as String
            api.startRemoteEnrollment(remoteEnrollmentIdArg) { result ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(result.getOrNull()))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.startRemoteVerification$separatedMessageChannelSuffix",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val remoteSessionIdArg = args[0] as String
            api.startRemoteVerification(remoteSessionIdArg) { result ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(result.getOrNull()))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.isInitialized$separatedMessageChannelSuffix",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isInitialized())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.usesense_flutter.UseSenseHostApi.reset$separatedMessageChannelSuffix",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.reset()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UseSenseFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    val codec: MessageCodec<Any?> by lazy { UseSensePigeonCodec }
  }

  fun onEvent(eventArg: PigeonUseSenseEvent, callback: (Result<Unit>) -> Unit) {
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.usesense_flutter.UseSenseFlutterApi.onEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2])))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }

  fun onCancelled(callback: (Result<Unit>) -> Unit) {
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.usesense_flutter.UseSenseFlutterApi.onCancelled$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String?, it[2])))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      }
    }
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error", "Unable to establish connection on channel: '$channelName'.", "")
}
